biomes:
  - minecraft:deep_frozen_ocean
  - minecraft:frozen_ocean
  - minecraft:frozen_peaks
  - minecraft:frozen_river
  - minecraft:grove
  - minecraft:ice_spikes
  - minecraft:jagged_peaks
  - minecraft:snowy_beach
  - minecraft:snowy_plains
  - minecraft:snowy_slops
  - minecraft:snowy_taiga

freeze-ticks: 20 # Amount to ticks to be added every freezing effect

effects:
  enabled: true # This enables/disables effects only, not damage
  delay: 5 # Time in seconds to wait to start having effects
  interval: 5 # Time in seconds to give effects everytime
  damage:
    enabled: true
    value: 1.0 # Value to damage player
  effects:
    - blindness:
        time: 5 # Time of effect
        amplifier: 0 # Amplifier of effect, set to 0 for level 1
    - slowness:
        time: 10
        amplifier: 0

cold-protection:
  wearing-leather-armor:
    enabled: true
    count: 4 # This tells how many armor you have e.g. 4 means 4 armour items (Full leather armor)
  have-fire-enchantment:
    enabled: true
    level: 1
    count: 4
  have-fire-resistance:
    enabled: true
  near-heat-source:
    enabled: true
    radius: 5
    heat-sources:
      - minecraft:lava
      - minecraft:campfire
      - minecraft:soul_campfire

messages: true

disable-join-message: false