name: Frostbite
version: '1.0.2'
main: com.umnirium.mc.frostbite.Frostbite
description: Realistic Cold Exposure in Minecraft
author: ixcharles
website: https://github.com/ixcharles
api-version: '1.21.5'